[package]
name = "kernel-hasher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10"
linux-loader = { version = "0.6.0", features = ["elf", "bzimage"] }
vm-memory = "0.9.0"